name: "Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the Environment to Deploy (dev, qut, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qut
          - prod

jobs:
  deploy:
    name: "Deploy to ${{ github.event.inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Set AWS Role ARN
        run: |
          echo "Setting up AWS credentials"
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "AWS_ROLE_ARN=${{ secrets.AWS_DEV_ROLE_ARN }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "qut" ]]; then
            echo "AWS_ROLE_ARN=${{ secrets.AWS_QUT_ROLE_ARN }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "AWS_ROLE_ARN=${{ secrets.AWS_PROD_ROLE_ARN }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Initialize Terraform
        run: terraform init -backend-config=environments/${{ github.event.inputs.environment }}/backend.tf

      - name: Plan Terraform
        run: terraform plan -var-file=environments/${{ github.event.inputs.environment }}/terraform.tfvars

      - name: Apply Terraform
        run: terraform apply -auto-approve -var-file=environments/${{ github.event.inputs.environment }}/terraform.tfvars
